# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
np.show_config(mode = 'stdout')
#np.__version__




Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/KaoticCharma/anaconda3/Library/include
    lib directory: C:/Users/KaoticCharma/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/KaoticCharma/anaconda3/Library/include
    lib directory: C:/Users/KaoticCharma/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:
    commands: cython
    linker: cython

In [3]:
print("Numpy Version : ",np.__version__)

Numpy Version :  2.3.5


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [4]:
### [your code here]
arr = np.random.rand(2, 3, 5)
arr
a = arr
a.shape

(2, 3, 5)


### 4. Print a.


In [5]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
result = arr * 2
print(result)

[ 2  4  6  8 10]


In [6]:
### [your code here]
print(a)
a.shape

[[[0.31303977 0.69253164 0.83948495 0.1564514  0.13376527]
  [0.40367987 0.62634502 0.04195783 0.98440333 0.71379805]
  [0.25202793 0.24043304 0.13326423 0.3835107  0.40805134]]

 [[0.19398452 0.66007143 0.06803705 0.49124813 0.11800345]
  [0.32604145 0.26479828 0.60645409 0.52591619 0.27351171]
  [0.60652494 0.3599074  0.35132693 0.10126275 0.14560665]]]


(2, 3, 5)

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [7]:
### [your code here]
onesonly1 = np.ones((5,2,3),dtype=int)
onesonly1
b = onesonly1


### 6. Print b.


In [8]:
### [your code here]
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [9]:
### [your code here]
if a.size == b.size:
    print("Size of a:",a.size) ;print("Size of b:",b.size)
else: 
    print("Shape of a:",a.shape); print("Shape of b:",b.shape)
   

Size of a: 30
Size of b: 30



### 8. Are you able to add a and b? Why or why not?


In [10]:
### [your code here]

print(a.shape)
print(b.shape)
print(""" As broadcasting is based on the spcific rule : 
      Either the Dimension of the 2 Matrices is Compatible ie same or 1. As here the Dimensions are not same. """)
print("But here are 3 ways to do it properly.")

# Expanding the given matrices : expanded_a and expanded_b

a_exp = np.expand_dims(a, axis=0)
b_exp = np.expand_dims(b, axis=-1)

a_broad,b_broad = np.broadcast_arrays(a_exp,b_exp)

result_expanded = np.add(a_broad,b_broad)
print(f'''\n So now the addition works as i am able to expand the Dimensions and add
      using the rules of Broadcasting attribute of numpy: \n {result_expanded}''')


# Adding new axis : 

a_newaxis = a[np.newaxis,:,:,:]
b_newaxis = b[:,:,:,np.newaxis]
result_newaxis = a_newaxis+b_newaxis

print(f'''\n So now the addition works as i am able to add a new axis and simply add
      without using the broadcasting attribute of numpy:\n {result_expanded}''')

# Adding by injecting a 'NONE' ie size 1 axis

a_size1axis = a[None,...]
b_size1axis = b[...,None]

result_size1axis = a_size1axis+b_size1axis

print(f'''\n So now the addition works as i am able to inject a size 1 axis and simply add
      using the broadcasting rules of numpy:\n {result_expanded}''')


(2, 3, 5)
(5, 2, 3)
 As broadcasting is based on the spcific rule : 
      Either the Dimension of the 2 Matrices is Compatible ie same or 1. As here the Dimensions are not same. 
But here are 3 ways to do it properly.

 So now the addition works as i am able to expand the Dimensions and add
      using the rules of Broadcasting attribute of numpy: 
 [[[[1.31303977 1.69253164 1.83948495 1.1564514  1.13376527]
   [1.40367987 1.62634502 1.04195783 1.98440333 1.71379805]
   [1.25202793 1.24043304 1.13326423 1.3835107  1.40805134]]

  [[1.19398452 1.66007143 1.06803705 1.49124813 1.11800345]
   [1.32604145 1.26479828 1.60645409 1.52591619 1.27351171]
   [1.60652494 1.3599074  1.35132693 1.10126275 1.14560665]]]


 [[[1.31303977 1.69253164 1.83948495 1.1564514  1.13376527]
   [1.40367987 1.62634502 1.04195783 1.98440333 1.71379805]
   [1.25202793 1.24043304 1.13326423 1.3835107  1.40805134]]

  [[1.19398452 1.66007143 1.06803705 1.49124813 1.11800345]
   [1.32604145 1.26479828 1.60645409 1.



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [11]:
### [your code here]
print(b)
print(b.shape)
c = b.T
print(c.shape)
print(a.shape)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(5, 2, 3)
(3, 2, 5)
(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [12]:
### [your code here]
print("As broadcasting is based on the spcific rule : Either the Dimension of the 2 Matrices is Compatible ie same or 1. As here the Dimensions are not same.")
d = a + np.ones(1,) 
print(f"shape of A = {a.shape}")
print(f"shape of B = {b.shape}")
print(f"shape of C = {c.shape}")
print(''' The shapes of 'a' and 'c' are not compatible for according to the broadcasting rules , so we will use einsum ''')

result_einsum = a + np.einsum('jik->ijk',c)
print(f'''After using einsum i am able to add the 2 matrices.
      Shape of 'a' = \n{a.shape} and shape of 'c' = \n{c.shape} and resulting matirix is 
      Shape of final matrix =\n {result_einsum.shape} and its value = \n {result_einsum} ''')




As broadcasting is based on the spcific rule : Either the Dimension of the 2 Matrices is Compatible ie same or 1. As here the Dimensions are not same.
shape of A = (2, 3, 5)
shape of B = (5, 2, 3)
shape of C = (3, 2, 5)
 The shapes of 'a' and 'c' are not compatible for according to the broadcasting rules , so we will use einsum 
After using einsum i am able to add the 2 matrices.
      Shape of 'a' = 
(2, 3, 5) and shape of 'c' = 
(3, 2, 5) and resulting matirix is 
      Shape of final matrix =
 (2, 3, 5) and its value = 
 [[[1.31303977 1.69253164 1.83948495 1.1564514  1.13376527]
  [1.40367987 1.62634502 1.04195783 1.98440333 1.71379805]
  [1.25202793 1.24043304 1.13326423 1.3835107  1.40805134]]

 [[1.19398452 1.66007143 1.06803705 1.49124813 1.11800345]
  [1.32604145 1.26479828 1.60645409 1.52591619 1.27351171]
  [1.60652494 1.3599074  1.35132693 1.10126275 1.14560665]]] 



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [13]:
### [your code here]
print("\nThis is a =",a, "and shape of a = ", a.shape )
print('\n')
print('\n')
print('\n')
print("\nThis is d =",d, "and shape of d = ", d.shape)

print(" Matrix 'a' is added with 1 and d without addition of 1  ")



This is a = [[[0.31303977 0.69253164 0.83948495 0.1564514  0.13376527]
  [0.40367987 0.62634502 0.04195783 0.98440333 0.71379805]
  [0.25202793 0.24043304 0.13326423 0.3835107  0.40805134]]

 [[0.19398452 0.66007143 0.06803705 0.49124813 0.11800345]
  [0.32604145 0.26479828 0.60645409 0.52591619 0.27351171]
  [0.60652494 0.3599074  0.35132693 0.10126275 0.14560665]]] and shape of a =  (2, 3, 5)







This is d = [[[1.31303977 1.69253164 1.83948495 1.1564514  1.13376527]
  [1.40367987 1.62634502 1.04195783 1.98440333 1.71379805]
  [1.25202793 1.24043304 1.13326423 1.3835107  1.40805134]]

 [[1.19398452 1.66007143 1.06803705 1.49124813 1.11800345]
  [1.32604145 1.26479828 1.60645409 1.52591619 1.27351171]
  [1.60652494 1.3599074  1.35132693 1.10126275 1.14560665]]] and shape of d =  (2, 3, 5)
 Matrix 'a' is added with 1 and d without addition of 1  



### 12. Multiply a and c. Assign the result to e.


In [14]:
### [your code here]
print("as the dimensions of the 2 matrices are not same ,we will use einsum ")
print(''' 
The Logic of np.einsum :
When you call np.einsum('ijk,mik->ijm', A, C), you are passing two things: 
a string of dimension labels ('ijk,mik->ijm') and the matrices (A, C).
The engine follows three strict rules to figure out what mathematical operation to perform:
1. Alignment (Multiplication): If a letter appears in both input strings (like i and k), einsum knows it must 
multiply the elements along those axes together. It iterates through the shared dimensions exactly like a nested for loop.
2. Summation (Reduction): If a letter appears in the inputs 
but is missing from the output string after the -> arrow (like k in our example), 
einsum knows it must sum the results of the multiplication along that axis. This is the mathematical definition of a dot product.
3. Preservation (Element-wise): If a letter appears in the inputs and also in the output string 
(like i, j, and m), einsum keeps that dimension in the final tensor without summing it away.
​ ''')
result_einsum_mult = np.einsum('ijk,mik->ijm',a,c)
e = result_einsum_mult
print(f"the final answer is : {e}")

as the dimensions of the 2 matrices are not same ,we will use einsum 
 
The Logic of np.einsum :
When you call np.einsum('ijk,mik->ijm', A, C), you are passing two things: 
a string of dimension labels ('ijk,mik->ijm') and the matrices (A, C).
The engine follows three strict rules to figure out what mathematical operation to perform:
1. Alignment (Multiplication): If a letter appears in both input strings (like i and k), einsum knows it must 
multiply the elements along those axes together. It iterates through the shared dimensions exactly like a nested for loop.
2. Summation (Reduction): If a letter appears in the inputs 
but is missing from the output string after the -> arrow (like k in our example), 
einsum knows it must sum the results of the multiplication along that axis. This is the mathematical definition of a dot product.
3. Preservation (Element-wise): If a letter appears in the inputs and also in the output string 
(like i, j, and m), einsum keeps that dimension in the fina



### 13. Does e equal to a? Why or why not?


In [15]:
### [your code here]
print(e.shape)
print(a.shape)
print(''' 
The reason for difference = The difference in shape occurs because addition and true matrix multiplication 
are fundamentally different mathematical operations with entirely different sets of rules. They interact with dimensions differently.
When you add two arrays, you are performing an element-wise operation. 
When you multiply them using a dot product or matmul, you are performing an aggregation operation. 
''')

(2, 3, 3)
(2, 3, 5)
 
The reason for difference = The difference in shape occurs because addition and true matrix multiplication 
are fundamentally different mathematical operations with entirely different sets of rules. They interact with dimensions differently.
When you add two arrays, you are performing an element-wise operation. 
When you multiply them using a dot product or matmul, you are performing an aggregation operation. 





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [16]:
### [your code here]
print(d)
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(f"max of d = {d_max}")
print(f"min of d = {d_min}")
print(f"mean of d = {d_mean}")

[[[1.31303977 1.69253164 1.83948495 1.1564514  1.13376527]
  [1.40367987 1.62634502 1.04195783 1.98440333 1.71379805]
  [1.25202793 1.24043304 1.13326423 1.3835107  1.40805134]]

 [[1.19398452 1.66007143 1.06803705 1.49124813 1.11800345]
  [1.32604145 1.26479828 1.60645409 1.52591619 1.27351171]
  [1.60652494 1.3599074  1.35132693 1.10126275 1.14560665]]]
max of d = 1.9844033328667312
min of d = 1.0419578332063626
mean of d = 1.3805146449837242



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [17]:
### [your code here]
f = np.empty((2,3,5), dtype =None)
print(f"f = {f}")

f = [[[1.31303977 1.69253164 1.83948495 1.1564514  1.13376527]
  [1.40367987 1.62634502 1.04195783 1.98440333 1.71379805]
  [1.25202793 1.24043304 1.13326423 1.3835107  1.40805134]]

 [[1.19398452 1.66007143 1.06803705 1.49124813 1.11800345]
  [1.32604145 1.26479828 1.60645409 1.52591619 1.27351171]
  [1.60652494 1.3599074  1.35132693 1.10126275 1.14560665]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [18]:
### [your code here]
conditions = [
    np.isclose(d,d_min),
    np.isclose(d,d_max),
    np.isclose(d,d_mean),
    (d>d_min) & (d<d_mean),
    (d>d_mean) & (d<d_max)
]

choices = [0,100,50,25,75]
f = np.select(conditions,choices,default=-1)
print(f"\nValue of f =\n {f}")

### Another way to do it : 
for x in range(0,len(d.flat)):

   if (d_mean < d.flat[x]) and (d.flat[x] < d_max):
       f.flat[x] = 75
   if d_min < d.flat[x] < d_mean:
       f.flat[x] = 25
   if d.flat[x] == d_mean:
       f.flat[x] = 50
   if d.flat[x] == d_min:
       f.flat[x] = 0
   if d.flat[x] == d_max:
       f.flat[x] = 100
    
print(f)


Value of f =
 [[[ 25  75  75  25  25]
  [ 75  75   0 100  75]
  [ 25  25  25  75  75]]

 [[ 25  75  25  75  25]
  [ 25  25  75  75  25]
  [ 75  25  25  25  25]]]
[[[ 25  75  75  25  25]
  [ 75  75   0 100  75]
  [ 25  25  25  75  75]]

 [[ 25  75  25  75  25]
  [ 25  25  75  75  25]
  [ 75  25  25  25  25]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [19]:
### [your code here]
print(d)
print(f)


[[[1.31303977 1.69253164 1.83948495 1.1564514  1.13376527]
  [1.40367987 1.62634502 1.04195783 1.98440333 1.71379805]
  [1.25202793 1.24043304 1.13326423 1.3835107  1.40805134]]

 [[1.19398452 1.66007143 1.06803705 1.49124813 1.11800345]
  [1.32604145 1.26479828 1.60645409 1.52591619 1.27351171]
  [1.60652494 1.3599074  1.35132693 1.10126275 1.14560665]]]
[[[ 25  75  75  25  25]
  [ 75  75   0 100  75]
  [ 25  25  25  75  75]]

 [[ 25  75  25  75  25]
  [ 25  25  75  75  25]
  [ 75  25  25  25  25]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [20]:
### [your code here]
conditions = [
    np.isclose(d,d_min),
    np.isclose(d,d_max),
    np.isclose(d,d_mean),
    (d>d_min) & (d<d_mean),
    (d>d_mean) & (d<d_max)
]

choices = ['A','B','C','D','E']
f = np.select(conditions,choices,default='X')
print(f"\nValue of f =\n {f}")


Value of f =
 [[['D' 'E' 'E' 'D' 'D']
  ['E' 'E' 'A' 'B' 'E']
  ['D' 'D' 'D' 'E' 'E']]

 [['D' 'E' 'D' 'E' 'D']
  ['D' 'D' 'E' 'E' 'D']
  ['E' 'D' 'D' 'D' 'D']]]
